### ISSUE TITLE
[BUG]: change background color of search div to make icon visible

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/ScrapeIt#101]
# Actual: ![image](https://github.com/singodiyashubham87/ScrapeIt/assets/93720428/984d543a-4a6a-44da-97b4-0ca85001cce2)

# Expected: ![Screenshot from 2024-01-08 18-36-30](https://github.com/singodiyashubham87/ScrapeIt/assets/93720428/1aa719ea-20ac-4381-8441-67e189eda8de)

**Comment by sudeepkudari0** [comment]
started working on it

**Comment by sudeepkudari0** [comment]
@nepalivai Thanks for asking, I did work and merged the solution but I do not know y its not mentioned here and not yet closed

**Comment by nepalivai** [comment]
ohh nice!!!! now close the issue!
