### ISSUE TITLE
HTML scrape not working

### ISSUE THREAD

**Issue by slayeh17** [singodiyashubham87/ScrapeIt#180]
Hi, I am not sure if I am using it right but after I paste a link then click on `HTML` then click on `Scrape` it always returns the text format. It doesn't matter if I click on `Text` or 'HTML` it always returns the text only.

**Comment by singodiyashubham87** [comment]
@slayeh17 The scraping part is being done by the API provided by API Ninjas and they are sending it as text format only for some URLs which they can't scrape.

**Comment by slayeh17** [comment]
Ok got it. 👍
