### ISSUE TITLE
[Bug]: Make selection of one of the radio buttons mandatory before scraping

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/ScrapeIt#19]
If the user comes on the web app enters a URL and then clicks the Scrape button without choosing any of the radio buttons i.e. "Text-only" or "HTML" then the app gives the scraped which is not expected.

Add a check to ensure that one of the radio buttons is selected before scraping the data.

![image](https://github.com/singodiyashubham87/ScrapeIt/assets/93720428/97000f20-66e3-47f9-89da-bea1d47d74e6)

**Comment by IrfanSalim** [comment]
Hey, taking this up

**Comment by singodiyashubham87** [comment]
@IrfanSalim Go ahead!
