### ISSUE TITLE
[FEATURE] : Add light mode to the app

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/ScrapeIt#20]
Add a button to toggle between light and dark mode in the application.

**Comment by JAYBORICHA07** [comment]
@singodiyashubham87  If the issue is still open I would love to solve this issue and take my first step in to the KWOC.

**Comment by singodiyashubham87** [comment]
@JAYBORICHA07 I have assigned you an issue already, Have patience and once your PR is merged for that issue then I will comment on this issue and if not assigned already to someone, I'll assign this issue to you.

**Comment by ramith-kulal** [comment]
Can i work on it @singodiyashubham87  ?

**Comment by ayann07** [comment]
As a KWOC Contributor, I would want to work on this issue.

**Comment by singodiyashubham87** [comment]
@ayann07 Someone is already working on this issue, You can check out other issues or you can create your own issue describing the changes you want to make.

**Comment by singodiyashubham87** [comment]
@ayann07 Do you want to work on the issue now?

**Comment by ayann07** [comment]
Yes I want to work to work on this.

**Comment by singodiyashubham87** [comment]
@ayann07 Go Ahead!
