### ISSUE TITLE
[STYLE]: Change the scroll bar design 

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/ScrapeIt#21]
Enhance the scroll bar style by adding a border radius and changing color that fits the theme.

![image](https://github.com/singodiyashubham87/ScrapeIt/assets/93720428/76123d96-6538-4472-8190-fbe49e03d3f3)

**Comment by professorabhay** [comment]
Hey, @singodiyashubham87! Seems interesting. 
Let me do this. 
Kindly assign.

**Comment by singodiyashubham87** [comment]
@professorabhay Please be patient and work on one issue at a time, I've already assigned an issue to you.
Once that one is finished then comment on any other one.

**Comment by professorabhay** [comment]
@singodiyashubham87, raised the PR for the other one. Now, I would like to work on this. May I?

**Comment by singodiyashubham87** [comment]
@professorabhay Sure, Go Ahead!

**Comment by Tonystark121** [comment]
Hi @singodiyashubham87 , I would like to contribute to this issue; can you assign me this issue?
