### ISSUE TITLE
[FEATURE]: Add github icon that redirects to this repository 

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/ScrapeIt#22]
Add a GitHub icon on the top right corner of the app which when clicked redirects the user to this "ScrapeIt" repository.

**Comment by JonnyMc94** [comment]
Hi @singodiyashubham87, I would like to work on this issue if possible

**Comment by singodiyashubham87** [comment]
@JonnyMc94 Go Ahead & Best of Luck!

**Comment by R4Rohit23** [comment]
Hey Do you want to show this icon on both Home and Landing Page?

**Comment by singodiyashubham87** [comment]
@R4Rohit23 This issue is already assigned to @JonnyMc94, Please don't make any PR until you are assigned that issue.

**Comment by singodiyashubham87** [comment]
@JonnyMc94 Do you wish to continue working on the issue or should I assign it to @R4Rohit23 ?
I will wait for your reply till tomorrow at 11:00 AM IST, If there is no reply from your side until that time, I will assign the issue to someone else.

**Comment by JonnyMc94** [comment]
Hi @R4Rohit23 I am currently working on the issue and will push code tomorrow
