### ISSUE TITLE
[FIX]: Restructure the project

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/ScrapeIt#24]
The "Homepage.jsx", "LandingPage.jsx" and "Loader.jsx" files are in the components directory, add a new directory named "pages" and move "Homepage.jsx" and "LandingPage.jsx" to that directory and accordingly change all the file import paths too.

![image](https://github.com/singodiyashubham87/ScrapeIt/assets/93720428/faf035ce-4880-4b8e-a04c-04c4c2329da7)

**Comment by JAYBORICHA07** [comment]
@singodiyashubham87  if this issue isn't closed yet would love to contribute.

**Comment by singodiyashubham87** [comment]
@JAYBORICHA07 Go ahead!

**Comment by JAYBORICHA07** [comment]
@singodiyashubham87   Okay
