### ISSUE TITLE
[FEATURE] : Change cursor to pointer on hover

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/ScrapeIt#28]
Change the mouse cursor to pointer on hover over the radio buttons.

![image](https://github.com/singodiyashubham87/ScrapeIt/assets/93720428/c8ab7fbf-d864-48a0-aea6-badaf27532e0)

**Comment by IrfanSalim** [comment]
Hey, I would like to take this up

**Comment by singodiyashubham87** [comment]
Go ahead @IrfanSalim !
