### ISSUE TITLE
[DOCS] : Add the CONTRIBUTING.md file

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/ScrapeIt#32]
Add the CONTRIBUTING.md file defining some rules before contributing to the project:

1. You can create your own issues if you find something which need to be enhanced/fixed/modified in the project.
2. Ask to get the issue assigned to you before working on the issue & making a PR.
3. Don't create a PR until the issue is not assigned to you
4. Mention the issue number in the PRs
5. Describe all the changes that you have made briefly in the PR.

These are some of the main points which should be there in the file & other standard ones also you can add by yourself.

**Comment by IrfanSalim** [comment]
Hey, I'll take this up, please assign

**Comment by singodiyashubham87** [comment]
@IrfanSalim Go ahead!

**Comment by singodiyashubham87** [comment]
@IrfanSalim Is there any update regarding this issue?
