### ISSUE TITLE
[STYLE]: Decrease the size of the Modal 

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/ScrapeIt#43]
Decrease the size of the Modal and also take care of the responsiveness.

**
![image](https://github.com/singodiyashubham87/ScrapeIt/assets/93720428/51bb2ab3-acb5-4378-af30-53a9b35e06f6)
**

**Comment by smty2018** [comment]
@singodiyashubham87 can you please assign it to me

**Comment by singodiyashubham87** [comment]
Go ahead, @ritik48 .
Best of Luck!

**Comment by jasonzubiate** [comment]
I'd like to work on this, could get it done real quick

**Comment by singodiyashubham87** [comment]
@jasonzubiate It's already assigned to Ritik, If you would like to contribute to the project then you can create your own issues related to enhancements in the project or any bug fixes and I'll assign that to you.

**Comment by singodiyashubham87** [comment]
@ritik48 Are you still working on this issue?

**Comment by ritik48** [comment]
@singodiyashubham87 please review this pr
