### ISSUE TITLE
Rescrape by click Esc key

### ISSUE THREAD

**Issue by Abdelra6** [singodiyashubham87/ScrapeIt#46]
go to the landing page when Esc key is clicked

**Comment by Abdelra6** [comment]
@singodiyashubham87 Is it good now?

**Comment by singodiyashubham87** [comment]
@Abdelra6 But I don't think it's necessary, there is already a dedicated button for this functionality and how will the user know that he/she can ReScrape by clicking the Esc key?
I don't see any benefit of doing this, if you do then do explain to me too what's the problem without the Esc button that this issue will resolve, Maybe I'm not able to understand you clearly?

**Comment by Abdelra6** [comment]
It was just a suggestion that I thought it's good. I think it's common to close pop-ups by clicking The Esc key in alot of Apps

**Comment by Abdelra6** [comment]
Let me know If should work on it or close it

**Comment by singodiyashubham87** [comment]
@Abdelra6 I don't think there is a need for this as of now, So I'm closing this issue, Maybe you can create a better one.

**Comment by Abdelra6** [comment]
No problem.
