### ISSUE TITLE
[STYLE]: Change the background color of selected text

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/ScrapeIt#47]
Change this dark blue colour to a neutral palette to make it look soothing to the eyes.

![image](https://github.com/singodiyashubham87/ScrapeIt/assets/93720428/1d622f17-1e82-43f4-92f9-798d792a4849)

**Comment by nepalivai** [comment]
Can you describe the issue in brief? It is by default blue in the cade at the moment.
<img width="534" alt="image" src="https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/0439bb2b-9677-4516-90b0-d95db2e5fcce">

**Comment by singodiyashubham87** [comment]
@nepalivai By default, it's always blue but we can change it according to our needs.
I want it to be of some light color palette in the app.

**Comment by nepalivai** [comment]
@singodiyashubham87 Ohh i see. so you want to change to change the colour of the selected section. while selecting. Am I correct??

**Comment by singodiyashubham87** [comment]
@nepalivai Yep, you are correct.
I don't have any preferred color scheme for this, you can try any neutral color palette & can share me the screenshot, I'll tell you which one to go with.

**Comment by nepalivai** [comment]
@singodiyashubham87 that sounds great. So can you assign me this issue!

**Comment by singodiyashubham87** [comment]
Sure, @nepalivai !

**Comment by nepalivai** [comment]
<img width="478" alt="image" src="https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/bd7519f1-8c1b-4e66-8f6d-6e20ef28c9fe">
SO what are your thought's? @singodiyashubham87

**Comment by singodiyashubham87** [comment]
@nepalivai Use neutral color palatees like some light color tones, this one is so saturated.

**Comment by nepalivai** [comment]
So like,
Name: Pale Cerulean
Hex: #9CC0E7
RGB: (156, 192, 231)

For highlights and white for text?

**Comment by singodiyashubham87** [comment]
@nepalivai Let's discuss about these colors on discord server https://discord.com/invite/uK3C63T5
