### ISSUE TITLE
[STYLE]: Change heart icon color to red

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/ScrapeIt#48]
Change the color of this heart icon from cyan to red.

![image](https://github.com/singodiyashubham87/ScrapeIt/assets/93720428/8328b786-f4d0-4f25-9d6d-6e7667b00360)

**Comment by Jaimin25** [comment]
I would like to work on this

**Comment by Jaimin25** [comment]
@singodiyashubham87 I would like to work on this

**Comment by singodiyashubham87** [comment]
@Jaimin25 Go Ahead!
