### ISSUE TITLE
[FEAT]: Github repo. should open in new tab on clicking Github icon

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/ScrapeIt#49]
The GitHub icon should redirect to the GitHub repository of ScrapeIt in a new tab and not the same tab.

![image](https://github.com/singodiyashubham87/ScrapeIt/assets/93720428/a3684ae9-d74d-4cc5-b25d-0efec18e3650)

**Comment by Kiran1689** [comment]
@singodiyashubham87  Please assign this issue to me

**Comment by singodiyashubham87** [comment]
Go Ahead, @Kiran1689 !
