### ISSUE TITLE
[docs] : Update README.md file.

### ISSUE THREAD

**Issue by nepalivai** [singodiyashubham87/ScrapeIt#53]
A few grammatical issues were found in the README.md file.

Examples:- missing Period in the tech stack section.

<img width="474" alt="image" src="https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/c370e494-e157-4502-9565-14749018df7d">

**Comment by nepalivai** [comment]
Please assign me the following issue. I would like to work on it.

**Comment by singodiyashubham87** [comment]
Go Ahead, @nepalivai !
