### ISSUE TITLE
[feat] : create a new over all color theme for the web site.

### ISSUE THREAD

**Issue by nepalivai** [singodiyashubham87/ScrapeIt#59]
As I was searching for a new issue today. I felt like there was not much context for the web page theme as the new light mode (#58) {with all due respect, great work!!!} lacked some contrast and made the site look dull. So I thought considering a new color scheme for the site from free tools like Coolors would be nice. 

plus adding new designs for all buttons and divs according to new trends would also be great.

**Comment by singodiyashubham87** [comment]
@nepalivai Seems good, I'm assigning the issue to you, Go Ahead.
