### ISSUE TITLE
[BUG] Footer alignment not responsive.

### ISSUE THREAD

**Issue by nepalivai** [singodiyashubham87/ScrapeIt#60]
After the dimensions get less than 320, the Footer starts to stick to the left.
<img width="388" alt="image" src="https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/acc85ac6-f6e2-4246-99e2-a8b186efb8bc">

Expected:- 
centered align.

**Comment by nepalivai** [comment]
I want to work in the issue

**Comment by singodiyashubham87** [comment]
@nepalivai Go ahead!
