### ISSUE TITLE
[BUG] Hover effect on new light mode button.

### ISSUE THREAD

**Issue by nepalivai** [singodiyashubham87/ScrapeIt#65]
There is no hover effect on light and dark mode button.

**Comment by nepalivai** [comment]
I want to work on the issue.

**Comment by singodiyashubham87** [comment]
@nepalivai You are already assigned an issue, Kindly complete that one before taking up any other issue.

**Comment by ayann07** [comment]
I would like to work on this

**Comment by nepalivai** [comment]
Sorry for the inconvenience @singodiyashubham87, But as I told you that is going to take some time, I have already completed the work and was waiting to create a PR until you assigned me the issues.

**Comment by singodiyashubham87** [comment]
@nepalivai Oh..Okay..Go Ahead!

**Comment by nepalivai** [comment]
hey @singodiyashubham87, work is done waiting for review.

**Comment by nepalivai** [comment]
@singodiyashubham87 can we both agree that the bug is fixed?

**Comment by singodiyashubham87** [comment]
@nepalivai Which bug?

**Comment by nepalivai** [comment]
@singodiyashubham87  when this issue was open there was no hover effect on the light and dark mode button.

**Comment by singodiyashubham87** [comment]
@nepalivai Oh you are talking about the hover effect, it was an enhancement, not a bug, buddy. And yes, it's done.
