### ISSUE TITLE
[ENHANCEMENT]: Add new modern style search and button style.

### ISSUE THREAD

**Issue by nepalivai** [singodiyashubham87/ScrapeIt#80]
search bar inspiration.
![image](https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/38b5c35f-58f3-4a81-be82-c3e63ce76b50)

button inspiration.
![image](https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/d3fa7944-cc32-4b3b-98f9-7b92f0074382)

**Comment by singodiyashubham87** [comment]
@nepalivai Both are amazing, would love to have them in the app, do you want to implement them?

**Comment by nepalivai** [comment]
@singodiyashubham87 yep! for sure.

**Comment by singodiyashubham87** [comment]
@nepalivai Go Ahead!

**Comment by nepalivai** [comment]
@singodiyashubham87 what would be the best logo to keep on scrape button?
