### ISSUE TITLE
[ENHACEMENT]: New light mode and dark mode  button

### ISSUE THREAD

**Issue by nepalivai** [singodiyashubham87/ScrapeIt#81]
now
<img width="151" alt="image" src="https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/792656de-aeda-4e59-86a9-95406b4a173c">

enhancement:
![image](https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/1ee78871-ba36-4c50-8d6c-7e5ca67f646b)

**Comment by chetu2** [comment]
I would like to work on this. Can I be assigned to this issue?

**Comment by singodiyashubham87** [comment]
@nepalivai Do you want to work on this issue?

**Comment by singodiyashubham87** [comment]
@chetu2 According to the guidelines, the person who created the issue will get the most priority and if he/she does not want to work on the issue then the issue will be served on an FCFS(First come First Serve) basis.
So, If @nepalivai refuses to take the issue then I'll assign it to you, in the meantime you can go through the project and create your issue if you find something that can be enhanced/modified to make the web app better.
Good Luck :)

**Comment by chetu2** [comment]
@singodiyashubham87 got it sir

**Comment by nepalivai** [comment]
@singodiyashubham87 why don't we give @chetu2 A chance to work on the isssue.

**Comment by singodiyashubham87** [comment]
@nepalivai Appreciate your spirit.

**Comment by singodiyashubham87** [comment]
@chetu2 You can proceed now, I have assigned you the issue.

**Comment by nepalivai** [comment]
@chetu2 Here is something that will help you with the issue.  [(only use in worst case.)](https://www.youtube.com/watch?v=odqNMNKccjE)

**Comment by chetu2** [comment]
@singodiyashubham87 have a look

**Comment by singodiyashubham87** [comment]
@chetu2 Your PR has merge conflicts, resolve them.

**Comment by nepalivai** [comment]
seems like he dropped the project may I give it a try?
