### ISSUE TITLE
[ENHANCEMENT]: New check box style.

### ISSUE THREAD

**Issue by nepalivai** [singodiyashubham87/ScrapeIt#82]
Now 
<img width="329" alt="image" src="https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/cda667d4-4346-4a49-8cb6-c39320320b2e">

After completion
<img width="170" alt="image" src="https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/367449c2-d404-4832-81d3-de56a414e0e8">

**Comment by singodiyashubham87** [comment]
@nepalivai Seems nice, Want to get assigned?

**Comment by nepalivai** [comment]
@singodiyashubham87 okey!

**Comment by nepalivai** [comment]
default and hover.
<img width="395" alt="image" src="https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/edb1cb24-e471-4031-8015-075729e43947">

hover and active.
<img width="441" alt="image" src="https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/852403dc-f5f0-4a12-bb02-2339e957e678">

default and active
<img width="396" alt="image" src="https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/c3d4e340-64c3-41fb-8e5f-2a3a3e0ff161">
