### ISSUE TITLE
[BUG]: can't see selection on the search box.

### ISSUE THREAD

**Issue by nepalivai** [singodiyashubham87/ScrapeIt#83]
The selection and the search box have the same light colour. It's hard to see where the selection was made.

<img width="316" alt="image" src="https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/460b05f4-3c19-46f8-a84c-2c3b03191094">

**Comment by singodiyashubham87** [comment]
@nepalivai Want to work on this?

**Comment by nepalivai** [comment]
@singodiyashubham87 okey! I can work on the issue.
