### ISSUE TITLE
Text Visibility issue

### ISSUE THREAD

**Issue by AaadityaG** [singodiyashubham87/ScrapeIt#94]
if the browser is not supporting the message text is not visible...

![Capture](https://github.com/singodiyashubham87/ScrapeIt/assets/114663382/63311d40-9ce1-4ebd-a2df-4e6376a72ccd)

please allow me to work on it under KWoC tag

**Comment by singodiyashubham87** [comment]
@AaadityaG Want to work on the issue?
By the way which browser and version are you using?

**Comment by AaadityaG** [comment]
Yes I want to work on it

**Comment by singodiyashubham87** [comment]
@AaadityaG Go Ahead!

**Comment by nepalivai** [comment]
hey @singodiyashubham87 mind if i work on the issue?

**Comment by singodiyashubham87** [comment]
@nepalivai Yeah Sure.
